### ISSUE TITLE
Виснет страница при попытке сменить маркированный список

### ISSUE THREAD

**Issue by Deadly299** [vova07/yii2-imperavi-widget#103]
В браузере chrome, yandex если выделить маркированный список и попытаться его убрать - страница виснет.
На firfox все отлично.
http://joxi.ru/bmoJ86nUMQJb7r

**Comment by vova07** [comment]
Перед сегодняшним реализм проверил скрипт в некоторых браузеров, включая те что вы указали.
Ошибку не смог воспроизвести. Хотя если она даже и осталась в данной обертке, я не уверен что я смогу её решить. дело скорее всего в самом JS расширении.
