### ISSUE TITLE
.size() vs .lenght

### ISSUE THREAD

**Issue by r4cdv** [vova07/yii2-imperavi-widget#104]
It is necessary to replace ".size()" with ".lenght"
file redactor.js
Otherwise, an error occurs

**line 6913**
`if ($current.closest(element).lenght > 0)`

**line 1463**
`if ($(e.target).closest('.redactor-editor, .redactor-toolbar, .redactor-dropdown').lenght !== 0)`

**Comment by ta4** [comment]
same error

**Comment by angoliar** [comment]
+1

**Comment by AlexNyskil** [comment]
+1

**Comment by SereiaMaster** [comment]
Change all size() for lenght in redactor.js.

Change Asset.php

`
public $js = [
	    'redactor.min.js'
	];
`

for 

`
public $js = [
	    'redactor.js'
	];
`

Clean aplication assets... F5.. and works.

**Comment by magsarjav** [comment]
Tnx, also redactor.js should be minified again because its much larger than redactor.min.js

**Comment by onmotion** [comment]
#106 fix this
