### ISSUE TITLE
Problems with latest yii version

### ISSUE THREAD

**Issue by asmythe** [vova07/yii2-imperavi-widget#105]
I just updated to yii 2.0.13 and now the widget is really screwing up. Looks like the one in this package is 10.2.5 from 2015, whereas the latest one is 2.11. Any plans to upgrade to the latest imperavi code? Any suggests on how to get it behave with yii2. Here are the js errors I'm getting:

TypeError: $(e.target).closest('.redactor-editor, .redactor-toolbar, .redactor-dropdown').size is not a function. (In '$(e.target).closest('.redactor-editor, .redactor-toolbar, .redactor-dropdown').size()', '$(e.target).closest('.redactor-editor, .redactor-toolbar, .redactor-dropdown').size' is undefined)

and

[Error] TypeError: $current.closest(element).size is not a function. (In '$current.closest(element).size()', '$current.closest(element).size' is undefined)
	(anonymous function) (Anonymous Script 1 (line 1:127107))
	each (jquery.js:362)
	dropdowns (Anonymous Script 1 (line 1:126821))
	dropdowns
	toolbar (Anonymous Script 1 (line 1:126579))
	toolbar
	dispatch (jquery.js:5206)

**Comment by sskyspear** [comment]
same +1

**Comment by RStuffGit** [comment]
+1

**Comment by asmythe** [comment]
I ended up springing for the commercial version and manually replacing the bower files with the commercial ones. Works, but I worry they will eventually get overwritten. Be great if the latest Yii widget was the latest version of Redactor.

**Comment by prsolucoes** [comment]
+1 Anyone solve this problem?

**Comment by NikoVonLas** [comment]
+1
https://github.com/vova07/yii2-imperavi-widget/issues/104
