### ISSUE TITLE
Не появляется картинка в редакторе

### ISSUE THREAD

**Issue by luckyalexandr** [vova07/yii2-imperavi-widget#107]
При добавлении картинки все проходит гладко, но картинка в редакторе не появляется... Ни отображения ни кода - пустота.
Никаких ошибок не алертит, файл благополучно загружается в указаную директорию.

В экшене:

>    return [
>             'error' => [
>                 'class' => 'yii\web\ErrorAction',
>             ],
>             'image-upload' => [
>                 'class' => 'vova07\imperavi\actions\UploadAction',
>                 'url' => 'http://test.loc/admin/upload/imperavi/', // URL адрес папки куда будут загружатся изображения.
>                 'path' => Yii::getAlias('@webroot/upload/imperavi') // Или абсолютный путь к папке куда будут загружатся изображения.
>             ],
>             'images-get' => [
>                 'class' => 'vova07\imperavi\actions\GetAction',
>                 'url' => 'http://test.loc/admin/upload/imperavi/', // Directory URL address, where files are stored.
>                 'path' => Yii::getAlias('@webroot/upload/imperavi'), // Or absolute path to directory where files are stored.
>                 'type' => 1,
>             ],
> ];

Если прописать 'type' => GetAction::TYPE_FILES, выдает ошибку `Class 'backend\controllers\GetAction' not found`

Во view:

>       <?= $form->field($model, 'content')->widget(Widget::className(), [
>                 'settings' => [
>                     'imageUpload' => Url::to(['/news/image-upload']),
>                     'imageManagerJson' => Url::to(['/news/images-get']),
>                     'plugins' => [
>                         'clips',
>                         'fullscreen',
>                         'imagemanager'
>                     ]
>                 ]
>             ]); ?>

Обидно.. Раньше все работало чудесно

**Comment by vova07** [comment]
Приветствую!
Можете проверить вашу ситуацию используя код из этого ПР-а: https://github.com/vova07/yii2-imperavi-widget/pull/108, и вот такую правку в контролере:
```php
public function actions()
 {
    ...
     return [
         'get-image' => [
             'class' => GetImagesAction::className(),
             'url' => 'http://my-site.com/statics/',
             'path' => '/var/www/my-site.com/web/statics',
             'options' => ['only' => ['*.jpg', '*.jpeg', '*.png', '*.gif', '*.ico']],
         ]
     ];
 }
```

**Comment by vova07** [comment]
Скорее всего этот баг был решён в новой версии.
Если проблема еще осталась, откройте пожалуйста заново эту тему.
