### ISSUE TITLE
Не передаётся токен csrf

### ISSUE THREAD

**Issue by VGrigoryev** [vova07/yii2-imperavi-widget#11]
В Widget::init устанавливается параметр uploadFields, которого нет в redactor.js и соответственно ключ не передаётся на сервер и вызывает exception 'yii\web\BadRequestHttpException' with message 'Не удалось проверить переданные данные.'

Если заменить

``` php
$this->settings['uploadFields'][Yii::$app->request->csrfParam] = Yii::$app->request->getCsrfToken();
```

На:

``` php
$this->settings['uploadImageFields'][Yii::$app->request->csrfParam] = Yii::$app->request->getCsrfToken();
$this->settings['uploadFileFields'][Yii::$app->request->csrfParam] = Yii::$app->request->getCsrfToken();
```

загрузка начинает работать

**Comment by bartzushka** [comment]
$this->options['uploadImageFields'][Yii::app()->request->csrfTokenName] = Yii::app()->request->getCsrfToken();
		$this->options['uploadFileFields'][Yii::app()->request->csrfTokenName] = Yii::app()->request->getCsrfToken();
