### ISSUE TITLE
plugins icons don't appear if more than one widget placed in a form

### ISSUE THREAD

**Issue by sergmoro1** [vova07/yii2-imperavi-widget#112]
I placed 3 fields with a widget. Settings were not equal.

	<?= $form->field($model, 'excerpt')->widget(Widget::className(), [
		'settings' => [
			'lang' => 'ru',
			'minHeight' => 200,
			'plugins' => [
				'clips',
				'fullscreen',
			]
		]
	]); ?>

	<?= $form->field($model, 'content')->widget(Widget::className(), [
		'settings' => [
			'lang' => 'ru',
			'minHeight' => 200,
			'replaceDivs' => false,
			'fileUpload' => Url::to(['site/file-upload']),			
			'imageUpload' => Url::to(['site/image-upload']),
			'fileDelete' => Url::to(['site/delete-file']),
			'imageDelete' => Url::to(['site/delete-file']),
			'fileManagerJson' => Url::to(['site/get-files']),		
			'imageManagerJson' => Url::to(['site/get-images']),		
			'plugins' => [
				'clips',
				'fullscreen',
				'table',
			],
		],
		'plugins' => [
			'filemanager' => 'vova07\imperavi\bundles\FileManagerAsset',              
			'imagemanager' => 'vova07\imperavi\bundles\ImageManagerAsset',              
		],
	]); ?>

	<?= $form->field($model, 'resume')->widget(Widget::className(), [
		'settings' => [
			'lang' => 'ru',
			'minHeight' => 100,
			'plugins' => [
				'clips',
				'fullscreen',
				'table',
			]
		]
	]); ?>

If in a last field don't mention all needed plugins, then some of them will be disappeared in a previous fields.

**Comment by vova07** [comment]
Hi, 
I'll check it tomorrow and will try to solve it if the bug will be confirmed.
Thanks!

**Comment by sergmoro1** [comment]
логично.

**Comment by vova07** [comment]
Как я вижу вы русский язык понимаете, по этому пишу на русском.
Проверил вашу ситуацию, но к сожалению багу я не вижу.
Для подтверждения прикрепляю скришот на котором все редакторы со всеми кнопками.
![screen shot 2017-12-08 at 11 00 44 am](https://user-images.githubusercontent.com/2714082/33758574-72a9f29c-dc07-11e7-8f0e-40c6b30b8a8b.png)

**Comment by sergmoro1** [comment]
Добрый день! Вы попробовали убрать какой-ниюудь плагин, например table в последнем поле?

**Comment by vova07** [comment]
Приветствую!
Да, пробовал. Я не смог воспроизвести багу из-за кэша.
Щас я почистил кэш браузера и да, вижу этот баг, так что буду править.
Спасибо за репорт!

**Comment by sergmoro1** [comment]
Вам спасибо!
