### ISSUE TITLE
Counter Plugin

### ISSUE THREAD

**Issue by shoomlix** [vova07/yii2-imperavi-widget#114]
Доброго времени суток, Василий!

У меня простой вопрос, а как добавить плагин подсчёта слов в поле?

Я так понимаю нужно инициализировать коллбэк функцию, но на официальном сайте Imperavi только для Imperavi II, а для первой версии нет.

Как вызвать правильно эту коллбэк функцию, которая будет подсчитывать количество слов?

**Comment by vova07** [comment]
Приветствую Александр!
Как вы правильно заметили на офф сайте нет виджета который бы работал с версией редактора 10.2.3
По этому конкретный ответ на вопрос как это реализовать я дать не могу.
Но могу подсказать как правильно писать колбэки если это вам сможет помочь.

```php
echo \vova07\imperavi\Widget::widget([
    'name' => 'redactor',
    'settings' => [
        'lang' => 'ru',
        'plugins' => [
            'counter',
        ],
        'callbacks' => [
            'init: function() { this.counter.count(); }',
            'counter: function(data) { console.log(data); }'
        ],
    ],
]);
```
