### ISSUE TITLE
Не работает выделение жирным, курсивом и тд.

### ISSUE THREAD

**Issue by spdriver** [vova07/yii2-imperavi-widget#117]

**Comment by vova07** [comment]
Здравствуйте!
Попробуйте пожалуйста обновить `JQuery` до последней версии и протестируйте заново работу.
К сожалению я упустил момент когда JS библиотека перестала работать с более старыми версиями.

Напишите пожалуйста если это помогло или нет.

Спасибо!

**Comment by spdriver** [comment]
Здравствуйте!
Версия jQuery 3.2.1. Если напечатать текст и попробовать какое-нибудь слово выделить жирным, курсивом или зачеркнутым, то ничего не происходит.

**Comment by vova07** [comment]
Приветствую @spdriver !
Сегодня протестил вашу проблему.
К сожалению использую версию `JQ 3.2.1` я не смог воспроизвести этот баг.
Вероятнее всего у вас конфликт.
Будет прекрасно если вы откроете консоль браузера и продержите реальную причину.
без подробных деталей я не смогу вам помочь.
С уважением!

**Comment by spdriver** [comment]
Здравствуйте! Сейчас протестировал в браузерах IE11, Firefox и Opera. Проблема наблюдается только в опера. В консоли ошибок нет.

**Comment by vova07** [comment]
Спасибо за информацию!
Протестирую в опера.
Первое что могу предположить это баг самой JS библиотеки.
Попробую протестировать её из другого репозитория.

**Comment by bzz445** [comment]
я сделяль #135

**Comment by vova07** [comment]
Спасибо!
Буду считать что бага решена, в противном случае можете перекрыть этот репорт!
