### ISSUE TITLE
Callbacks

### ISSUE THREAD

**Issue by Mefistophell** [vova07/yii2-imperavi-widget#118]
Здравствуйте! В продолжении темы **Counter Plugin** хотел бы уточнить по поводу callbacks. Версия редактора 10.2.5. 
Callbacks указанным ниже способом не отрабатывают. 
```
echo \vova07\imperavi\Widget::widget([
    'name' => 'redactor',
    'settings' => [
        'lang' => 'ru',
        'plugins' => [
            'counter',
        ],
        'callbacks' => [
            'init: function() { this.counter.count(); }',
            'counter: function(data) { console.log(data); }'
        ],
    ],
]);
```

И вообще, не получается прикрутить их, даже по документации: https://imperavi.com/redactor/docs/upgrading-to-redactor-ii/

Удручает, что в самом коде _redactor.js_ я так же могу найти где и как регистрируются callbacks. 
Может быть у вас есть идеи, что может помочь?

**Comment by vova07** [comment]
Приветствую @Mefistophell !

Как я уже говорил именно тот плагин который вы указали написан для более раней версии.

Но вот что я могу сказать вам в помощь учитывая информацию на указанной ссылке:

Если в новых версиях редактора должно быть так:
```js
callbacks: {
    init: function()
    {
    }
}
```

**то в версии 10.2.5 должно быть вот так**

```js
initCallback: function()
{
}
``` 

Из этого следует что правильный код который надо использовать в моем виджете должно выглядеть примерно вот так:

```php
echo \vova07\imperavi\Widget::widget([
    'name' => 'redactor',
    'settings' => [
        'lang' => 'ru',
        'plugins' => [
            'counter',
        ],
        'initCallback: function() { this.counter.count(); }',
        'counterCallback: function(data) { console.log(data); }',
    ],
]);
```

Хочу еще раз заметить что это только демо код который может вам помочь решить вашу задачу.
Я не уверен что официальные плагины доступные сейчас на сайте совместимы с старыми версиями редактора. (Я лично пробовал подключать по просьбам в других тикетах пару из них,  но так и не получилось.)

Желаю вам удачи!

Если посчитаете мой ответ полным, закройте пожалуйста тему, если будут еще вопросы, пожалуйста задавайте их без проблем!

**Comment by Mefistophell** [comment]
Спасибо большое! 
Да, срабатывает по документации : https://imperavi.com/assets/pdf/redactor-documentation-10.pdf
```
$('#redactor').redactor({
  changeCallback: function() {
      console.log(this.code.get());
    }
});
```
Скажите пожалуйста, можно ли прикрутить callback после того как редактор был проинициализирован и загружен?

**Comment by vova07** [comment]
К сожалению в текущей версии виджета такого функционала нет.
Для решения подобных задачь, мне кажется вы можете воспользоваться чистым JS решением.

Подключаете вместе с редактором новый скрипт файл, и в нем с помощью языка добавляете нужные прототайп методы.

Удачи!

**Comment by Mefistophell** [comment]
Благодарю!

**Comment by Mefistophell** [comment]
Если кому-то поможет, то мне удалось повесить callback таким образом: 
```
'settings' => [
  'changeCallback' => new JsExpression("function() { console.log('callback message');  }")
]
```

**Comment by vova07** [comment]
Спасибо за информацию!
