### ISSUE TITLE
Text alignment translations incorrect for Latvian.

### ISSUE THREAD

**Issue by Sorinson** [vova07/yii2-imperavi-widget#119]
Text translation for aligning text left, center, right are incorrect.

file - src/assets/lang/lv.js

60:  align_left:    'Izlīdzināt pa labi',
61:  align_center:     'Izlīdzināt pa kreisi',
62:  align_right:     'Izlīdzināt pret centru', 

Should be:
60:  align_left:    'Izlīdzināt pa kreisi',
61:  align_center:     'Izlīdzināt pret centru',
62:  align_right:     'Izlīdzināt pa labi',

**Comment by vova07** [comment]
I'll change it today.
Thank you @Sorinson !
