### ISSUE TITLE
request body is empty

### ISSUE THREAD

**Issue by sinergycode** [vova07/yii2-imperavi-widget#125]
Code for view:
```
    <?= $form->field($model, 'text')->widget(Widget::className(), [
        'settings' => [
            'lang' => 'ru',
            'minHeight' => 200,
            'formatting' => ['p', 'blockquote', 'h2'],
            'imageUpload' => \yii\helpers\Url::to(['site/native-imperavi']),
            'plugins' => [
                'clips',
                'fullscreen',
                'imagemanager'
            ],
        ],
    ]); ?>
```
Code for controller:
```
    public function actions()
    {
        return [
            'native-imperavi' => [
                      'class' => 'vova07\imperavi\actions\UploadFileAction',
                      'url' => 'http://site.com/public_html/uploads/images/blog/',
                      'path' => '@images/blog',
              ],
        ];
    }
```

Yii2 debuger:
method	'POST'
isAjax	true
$_FILES - file	[
    'name' => 'aaaaa.png'
    'type' => 'image/png'
    'tmp_name' => 'E:\\Opse\\OSPanel\\userdata\\temp\\php78D5.tmp'
    'error' => 0
    'size' => 99568
]
Request Body - Empty.  

In the redactor ia have a small image with code:
`<p><img src="http://site.com/public_html/uploads/images/blog/5a7d9980893b5.png" "=""></p>`

"blog" directory is empty.

How to fix it?

**Comment by vova07** [comment]
@sinergycode not sure I've got the idea.
As far I see from your code that the image was uploaded with the name `5a7d9980893b5.png`.
What is the result you actually expect?

**Comment by sinergycode** [comment]
Please, hint where to look for the problem?

**Comment by vova07** [comment]
@sinergycode the problems is that I don't understand your issue at all.
What do you solve right now? 
What are you doing, and it goes wrong for you?

**Comment by sinergycode** [comment]
Redactor imperavi is installed, and it' working great.
The image upload option don't work.
All the information about the problem is in this topic.
If it's necessary i can provide more information...

**Comment by sinergycode** [comment]
Why image was uploaded with name 5a7d9980893b5.png?

**Comment by vova07** [comment]
@sinergycode because of this param: https://github.com/vova07/yii2-imperavi-widget/blob/master/src/actions/UploadFileAction.php#L92

You can disable the behavior like this:
```php
public function actions()
    {
        return [
            'native-imperavi' => [
                      'class' => 'vova07\imperavi\actions\UploadFileAction',
                      'url' => 'http://site.com/public_html/uploads/images/blog/',
                      'path' => '@images/blog',
                      'unique' => false,
              ],
        ];
    }
```

**But you should be aware that you'll not be able to upload the file with the same name more times.**
In case you'll need to replace the file with similar name, please take a look at this documentation section: https://github.com/vova07/yii2-imperavi-widget#upload-and-replace-a-file-with-the-same-name

**Comment by sinergycode** [comment]
Now the code from redactor is:
`<p><img src="http://site.com/public_html/uploads/images/blog/aaaaa.png">`
But the image is still small (10x10px):
![imperavi](https://user-images.githubusercontent.com/30791491/36039240-9670f83e-0dca-11e8-8db8-ccaa17d393a5.png)

**Comment by vova07** [comment]
@sinergycode are you sure that your `url` is specified right?
I suppose the problem is somewhere here: `http://site.com/public_html/uploads/images/blog/`
I think the wrong part is `public_html`.
Can you try to replace that param with `http://site.com/uploads/images/blog/` instead and retry?

**Comment by sinergycode** [comment]
![imp](https://user-images.githubusercontent.com/30791491/36039891-7e7f690c-0dcc-11e8-90d6-558c0c681276.png)

**Comment by sinergycode** [comment]
Thanks, you was write, the problem is in the url!
