### ISSUE TITLE
How can I get my current domain name?

### ISSUE THREAD

**Issue by 112Legion112** [vova07/yii2-imperavi-widget#126]
In the documentation, I need to specify the current domain name?

```
// DefaultController.php
public function actions()
{
    return [
        'file-upload' => [
            'class' => 'vova07\imperavi\actions\UploadAction',
            'url' => 'http://my-site.com/files/', // Directory URL address, where files are stored.
            'path' => '@alias/to/my/path', // Or absolute path to directory where files are stored.
            'uploadOnlyImage' => false, // For any kind of files uploading.
        ],
    ];
}
```

How can I get it?

My developer server has a different domain name with my production server.

**Comment by vova07** [comment]
Hi @112Legion112 ,
Your question is not actually related with my extension.
The problem you described is related with `environments` and `configurations`.
For more info please read these articles:
https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/structure-environments.md
http://www.yiiframework.com/doc-2.0/guide-concept-configurations.html#environment-constants

A real example: https://github.com/yiisoft/yii2-app-advanced/tree/master/environments

And a detailed articles about it: https://www.my-yii.com/learn/view-episode/how-to-create-and-use-environments-in-yii-2-basic-application-template

Hope it will help you.

FYI: The `url` can be `relative` too.

P.S. Feel free to re-open the issue, in case you have more questions about the widget.
