### ISSUE TITLE
При удалении картинки из редактора удалять ее из базы данных.

### ISSUE THREAD

**Issue by sinergycode** [vova07/yii2-imperavi-widget#129]
Добрый день @vova07 
В документации нашел callback который срабатывает при удалении изображения:
imageDeleteCallback.
Скажите пожалуйста как ее вставить в такие конструкции: 
```
<?= $form->field($model, 'text')->widget(Widget::className(), [
        'settings' => [
            'lang' => 'ro',
            'plugins' => [
                'imagemanager',
              ]
         ],
]); ?>
```
Если есть уже готовая настройка которая удаляет фото из базы данных при удалении из редактора, скажите пожалуйста как ею пользоваться.

**Comment by vova07** [comment]
Здравствуйте @sinergycode !
Вы спросили про удаление из БД, но я не уверен что я понял вас правильно.
Имеется ли введу что изображение хранится в БД либо же только УРЛ на это изображение?
В документации [есть пример](https://github.com/vova07/yii2-imperavi-widget/blob/master/README_RU.md#Включаем-менеджер-изображений-с-функционалом-удаления-изоражения) как можно использовать менеджер изображений с возможностью удаление самого файла, но я не уверен что это то что вам нужно.

Просто есть несколько понятий удаления изображения:
- Из списка менеджера изображений.
- В момент удаления картинки из самого редактора при нажатии на бхкспэйс.

Если уточните вопрос, то попробую ответить более корректно.

**Comment by sinergycode** [comment]
Спасибо за ответ!
В изображении более детальное объяснение вопроса:
![default](https://user-images.githubusercontent.com/30791491/37695643-738b47c4-2cd9-11e8-917e-846b8244bcd8.png)

**Comment by vova07** [comment]
Чтобы подключить нужный вам обработчик надо использовать следующий код:
```php
<?= $form->field($model, 'text')->widget(Widget::className(), [
        'settings' => [
            'lang' => 'ro',
            'plugins' => [
                'imagemanager',
              ],
              'imageDeleteCallback' => new \yii\web\JsExpression('function (url, image) { alert("Image was deleted!"); }'),
         ],
]); ?>
```

Готового функционала специально под этот случай нету, но вы можете использовать например дефолтный экшен `DeleteFileAction` на который нужно отправить `AJAX` запрос с названием файла в указанном в настройках параметром который по дефолту `fileName`.

Succes!

**Comment by sinergycode** [comment]
Спасибо за ответ.
Succes!

**Comment by vova07** [comment]
Если надо будет можете повторно открыть этот репорт!

**Comment by sinergycode** [comment]
@vova07 добрый день!
При попытке реализовать функционал, есть проблемы:
javascript file:
```
function deleteimg(url) {
      var fileName = url.substring(url.lastIndexOf('/')+1,url.length);
      $.ajax({
        type: 'POST', 
        url: '/admin/app-admin/file-delete', 
        data: { 
            fileName: fileName
        }, 
        dataType:'json',
        success: function(response) {
            console.log('ok');
            console.log(response);
        },
        error: function(e) {
            console.log('not sent');
            console.log(e.responseText); 
        }
      });
}
```
AppAdminController:
```
    public function actions()
    {
        return [
            'images-get' => [
                'class' => 'vova07\imperavi\actions\GetImagesAction',
                'url' => 'http://telita.md/web/upload/redactor/', // Directory URL address, where files are stored.
                'path' => '@app/web/upload/redactor/', // Or absolute path to directory where files are stored.
            ],
            'image-upload' => [
                'class' => 'vova07\imperavi\actions\UploadFileAction',
                'url' => 'http://telita.md/web/upload/redactor/', // Directory URL address, where files are stored.
                'path' => '@app/web/upload/redactor/', // Or absolute path to directory where files are stored.
            ],
            'file-delete' => [
                'class' => 'vova07\imperavi\actions\DeleteFileAction',
                'url' => 'http://telita.md/web/upload/redactor/', // Directory URL address, where files are stored.
                'path' => '@app/web/upload/redactor/', // Or absolute path to directory where files are stored.
            ],
        ];
    }
```
_form.php (вид):
```
            'plugins' => [
                'imagemanager',
                'table',
            ],
            'imageDeleteCallback' => new \yii\web\JsExpression(
                    'function(url) {deleteimg(url);}'
            ),
```
Получаю следующую ошибку:
/admin/app-admin/file-delete 400 (Bad Request)
Bad Request (#400): Only DELETE AJAX request is allowed

Скажите пожалуйста в чем может быть причина.

**Comment by vova07** [comment]
@sinergycode приветствую!
Причина в вашей функции: `deleteimg` где вы вместо `DELETE` запроса делаете `POST` вот тут:
```js
$.ajax({
    type: 'POST',
    ...
```
Дефолтный экшен редактора принимает только `DELETE` запрос вот он и ругается что не может ничего обработать в вашем случае.

**Comment by sinergycode** [comment]
Благодарю @vova07,
заработало,
Succes!

**Comment by sinergycode** [comment]
@vova07 добрый день.

Появились 2 вопроса:

1. При удалении фото появляется в консоли следующяя ошибка:
The given range isn't in document. VM884:1 

2. Есть Блог с постами.
Как при удалении поста, удалять  на сервере и изображения поста ткоторые были загружены через imperavi редактор.

**Comment by vova07** [comment]
@sinergycode добрый день!

1) Вероятнее всего это связанно с `Jquery` библиотекой: https://github.com/vova07/yii2-imperavi-widget/issues/116
Я не помню когда точно но кажется что та JS библиотека которая есть в моем виджете требует минимальную версию `Jquery 3`, надо будет проверить на днях.

2) Раз вы делаете запись каждого изображения в БД то лучше делать это через экшен загрузки файла. Это значит что вам надо будет написать его самостоятельно по подобию этого файла: https://github.com/vova07/yii2-imperavi-widget/blob/2.0.3/src/actions/UploadFileAction.php#L62 и делать параллельно запись и в БД.

Несмотря на это я бы предложил бы идти более легким и разумным путем: загружайте лучше все файлы одно поста в подпапку в имени которого добавляйте его уникальный ИД чтобы при удалении поста можно было разом всю папку удалить. Делать это конечно тоже лучше на бэкенде а не в процессе работы с вашим фронтоном.

**Comment by sinergycode** [comment]
1. Ошибка некритичная или лучше добавить jquery 3 если в этом причина?

2. Спасибо за совет - воспользуюсь Вашим методом.

**Comment by vova07** [comment]
1. Это уже на ваше усмотрение. Плюс я не уверен до конца в чем проблема. Лично у меня я не смог это воспроизвести, но использовал я только 3-ю версию.

**Comment by sinergycode** [comment]
Ок, спасибо!

**Comment by sinergycode** [comment]
2. А как заполучить следующий id конкретной модели?. Покопался в нете, но пока не нашел подходящего похода?

**Comment by sinergycode** [comment]
Нашел решение, но есть рикс что пост начную создавать, но CREATE не будет нажато.    

public function actionCreate()
    {
        $model = new Pages();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }
        $maxid = Pages::find()->select('id')->orderBy(['id' => SORT_DESC])->one();
        $nextid = $maxid->id +1;
                
        return $this->render('create', [
            'model' => $model,
            'nextid' => $nextid
        ]);
    }

**Comment by sinergycode** [comment]
Нашел отвтет:
```
<?php $lastModelId = Yii::$app->db->createCommand("
    SELECT `AUTO_INCREMENT`
    FROM  INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = DATABASE()
    AND   TABLE_NAME   = 'pages'
")->queryScalar();
    echo '<pre>' . print_r($lastModelId, true) . '</pre>';
    ?>
```
Может кому-то понадобится...

**Comment by vova07** [comment]
Мне кажется вы выбрали не самый лучший путь.

**Я лично сделал бы так:**
- В момент заполнения нового поста все изображения я бы хранил в временной папке.
- Как только пользователь нажимает на кнопку сохранить я бы отправлял данные на сервер для сохранения.
- В момент сохранения поста после того как он был добавлен в БД я мы перенес временную папку в основную директорию с названием которое содержало бы уникальный идентификатор модели, или что угодно чтобы потом можно было найти эту папку. (Можно даже в БД сохранить её название.)

Удаление уже логично понятное из описанного процесса выше!

**Comment by sinergycode** [comment]
На данный моент выжымают сроки. А поскольку админ будет только 1 человек, то ошибок не должно быть. Максимум что может быть это сохранение ненужных директорий с фотографиями в случае если админ при создании поста загрузил фото но не нажал сохранить.

В будущем сделаю вариант предложенный вами, СПАСИБО!

**Comment by sinergycode** [comment]
@vova07  добрый день.

Сменил версию jquery: jQuery JavaScript Library v3.2.1
1. The given range isn't in document. VM884:1  появляется тогда когда кликаю на изображение а потом удаляю ее.

2. Также когда пытаюсь работать с таблицей (добавить или удалить ряд) появляется ошибка:
Uncaught TypeError: $table.size is not a function
Код в форме для таблицы:
            'plugins' => [
                'table',
            ],

**Comment by vova07** [comment]
Добрый день!

Видимо того проблема именно в новой версии JQuery. Извиняюсь за конфуз.

1) Я попробую на днях посмотреть эту ошибку, но тут конфликт именно у JS библиотеки поэтому я не уверен что смогу исправить.

2) Подобный вопрос уже поднимали: https://github.com/vova07/yii2-imperavi-widget/issues/121 там есть описанное решение проблемы.

Думаю вам лучше вернутся на прежний версию JS чтобы избавить себя от лишних проблем.

Из-за того что библиотека JS сторонняя и уже устаревшая я не уверен что все ошибки можно будет исправить.

Спасибо за коммент!

**Comment by sinergycode** [comment]
a) Если сделаю изменения в vendor, какие будут последствия и что делать чтобы не случились эти последствия?
b) Можно ли подключать 2 jquery одновременно? Или подключить jquery меньше 3 версии только для редактора?

**Comment by sinergycode** [comment]
c). При апдейте любого виджета, будет осуществлен и update imperavi?
b). Этот вариант убираю.

**Comment by vova07** [comment]
a) Только если вы будете использовать `composer update`. В случае уникального обновления пакета `composer update vendor/repository` другие расширения не затрагиваются.

**Comment by sinergycode** [comment]
Благодарю за ответ!

Удачи!

**Comment by sinergycode** [comment]
Добрый день @vova07 ,
скажите пожалуйста что вы имели ввиду под:
"сделать ПР и смежить в мастер" ?

**Comment by vova07** [comment]
Добрый день @sinergycode !
Я имел введу что вы можете открыть `Pull Request` и я сделаю мердж и релиз новой версии.

**Comment by sinergycode** [comment]
К сожалению не очень понимаю что надо делать (знаю только основные команды в git console)

А как можно реализовать это вариант:
перекрыть основной Asset виджета и использовать файлы библиотеки из своего хранилища?

**Comment by allcho** [comment]
@vova07, Здравствуйте, а есть у вас рецепт, как удалять картинки из папки когда удаляешь полность пость со вставленными в него картинками

**Comment by vova07** [comment]
Здравствуйте @allcho !
К сожалению я уже очень давно не использую `Yii2` в работе, по этому готовый код я предоставить не смогу.
Но самый базовый план могу описать.
Самый легкий путь это сохранять изображения постов в подпапках с названием ИД поста.

Для примера:
```md
Posts:
1: Post 1
2: Post 2

Folders:
- files
-- 1
--- Image 1 for Post 1.jpg
--- Image 2 for Post 1.jpg
-- 2
--- Image 1 for Post 2.jpg
--- Image 2 for Post 2.jpg
```
Дальше в момент удаления поста, вам нужно просто удалить папку по ИД и все. Сделать это можно например через `beforeDelete` метод.

Другой подход это сохранять ссылки на файлы в БД в отдельной таблице, и потом в `beforeDelete` пробегаться по ним и удалять файлы вместе с записями, но это требует больше кода и бизнес логики.

Надеюсь мой ответ будет вам полезен.

Удачи!

**Comment by allcho** [comment]
> Здравствуйте @allcho !
> К сожалению я уже очень давно не использую `Yii2` в работе, по этому готовый код я предоставить не смогу.
> Но самый базовый план могу описать.
> Самый легкий путь это сохранять изображения постов в подпапках с названием ИД поста.
> 
> Для примера:
> 
> ```lisp
> Posts:
> 1: Post 1
> 2: Post 2
> 
> Folders:
> - files
> -- 1
> --- Image 1 for Post 1.jpg
> --- Image 2 for Post 1.jpg
> -- 2
> --- Image 1 for Post 2.jpg
> --- Image 2 for Post 2.jpg
> ```
> 
> Дальше в момент удаления поста, вам нужно просто удалить папку по ИД и все. Сделать это можно например через `beforeDelete` метод.
> 
> Другой подход это сохранять ссылки на файлы в БД в отдельной таблице, и потом в `beforeDelete` пробегаться по ним и удалять файлы вместе с записями, но это требует больше кода и бизнес логики.
> 
> Надеюсь мой ответ будет вам полезен.
> 
> Удачи!

Способ конечно хороший, спасибо. Но я зашул в тупик. Картинки сохрянятся при их загрузке, до того как я добавил пост. И я зашел в тупик, как это сделать, создават с ID постом, когда поста еще нет?

**Comment by vova07** [comment]
@allcho прочтите пожалуйста этот комментарий: https://github.com/vova07/yii2-imperavi-widget/issues/129#issuecomment-375728555
Думаю он должен вам помочь!
Если не будет понятно, то я попробую перефразировать.

**Comment by FedotKotov97** [comment]
В принципе вы можете сделать такой костыль=)): 
При добавлении картинки, когда поста еще нет, создается папка с рандомным именем, куда загружаются картинки в gridview, затем, когда пост уже создан, это имя директории заносится в таблицу Posts в колонку id_directory. Таким образом мы избежим одной и той же временной папки до создания поста у нескольких пользователей (если одновременно пост создают и картинки загружают), и без всяких перемещений директории сразу имеем ее в таблице Posts, ссылаясь на которую мы можем удалить вместе с картинками при удалении поста.



view добавления поста: 

`<?php

/** @var yii\web\View $this */
/** @var yii\bootstrap5\ActiveForm $form */
/** @var \common\models\Posts $model */

use yii\bootstrap5\Html;
use yii\bootstrap5\ActiveForm;
use vova07\imperavi\Widget;
use yii\helpers\Url;

$this->title = 'Создание поста';
$this->params['breadcrumbs'][] = $this->title;

$unique_dir = Yii::$app -> getSecurity() -> generateRandomString(7);
?>
<div class="form">
    <h1 style="color: #ececec"><?= Html::encode($this->title) ?>    </h1>

    <div class="row">
        <div>
            <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

            <?= $form->field($model, 'title')->textInput() ?>

            <?= $form->field($model, 'id_directory')->hiddenInput(['readonly' => true, 'value' => $unique_dir]) ?>

            <?= $form->field($model, 'post')->widget(Widget::className(), [
                'settings' => [
                    'lang' => 'ru',
                     'enctype'=>'multipart/form-data',
                    'minHeight' => 200,
                    'imageUpload' => Url::to(['/forum/savefile','unique_dir' => $unique_dir]),
                    'plugins' => [
                        'clips',
                        'fullscreen',
                    ],
                    'clips' => [
                        ['Lorem ipsum...', 'Lorem...'],
                        ['red', '<span class="label-red">red</span>'],
                        ['green', '<span class="label-green">green</span>'],
                        ['blue', '<span class="label-blue">blue</span>'],
                    ],
                ],
            ]); ?>

            <div class="form-group">
                <?= Html::submitButton('Создать', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>

            <?php ActiveForm::end(); ?>


        </div>
    </div>
</div>
`

controller:

`  public function actionNewpost()
    {
        $model = new Posts();
        if ($model->load(Yii::$app->request->post()) ) //&& $model -> picture = UploadedFile::getInstance($model, 'picture')
        {
            if($model -> addPost(Yii::$app -> request -> get('id'))) //&& $model -> picture -> saveAs("img/post/{$model->picture->baseName}.{$model->picture->extension}")
            {
                return $this->goBack('http://tforum/frontend/web/forum/categories');
            }
        }
        return $this->render('newpost', [
            'model' => $model
        ]);
    }


public function actionPostupdate()
{
    $model = Posts::findOne(Yii::$app -> request -> get('id'));
    if ($model -> load(Yii::$app -> request -> post()))
    {
        $model -> save();
        return $this  -> redirect(['post', 'id' => Yii::$app -> request -> get('id')]);
    }
    return $this -> render('postupdate', [
        'model' => $model,
        ]
    );


}




    public function actionSavefile($unique_dir = 'main')
    {

        //$this -> unique_dir = Yii::$app -> getSecurity() -> generateRandomString(7);
        $this -> enableCsrfValidation = false;
        if(Yii::$app -> request -> isPost)
        {
            $dir = Yii::getAlias('@img'). '/'. $unique_dir . '/';
            if (!file_exists($dir))
            {
                FileHelper::createDirectory($dir);
            }
            $result_link = Url::home(true). 'img/' . $unique_dir . '/';
            $file = UploadedFile::getInstanceByName('file');
            $model = new DynamicModel(compact('file'));
            $model -> addRule('file', 'image') -> validate();

            if($model -> hasErrors())
            {
                $result = ['error' => $model->getFirstError('file')];
            }
                else
                {
                    $model -> file -> name = strtotime('now').'_'. Yii::$app -> getSecurity() -> generateRandomString(6). '.'.$model -> file -> extension;

                    if($model -> file -> saveAs($dir . $model -> file -> name))
                    {
                        $imag = Yii::$app -> image -> load($dir . $model -> file -> name);
                        $imag -> resize(800, NULL, Yii\image\drivers\Image::PRECISE) -> save($dir . $model -> file -> name, 85);

                        $result = ['filelink' => $result_link . $model -> file -> name, 'filename' => $model -> file -> name];
                    }
                    else
                    {
                        $result = ['error' => Yii::t('vova07/imperavi', 'ERROR_CANT_UPLOAD_FILE!')];
                    }
                }
            Yii::$app->response->format = Response::FORMAT_JSON;
                    return $result;
        }
        else
        {
            throw new BadRequestHttpException('HZ!');
        }
    }`
