### ISSUE TITLE
Add custom clips

### ISSUE THREAD

**Issue by SlovyanskiyYehor** [vova07/yii2-imperavi-widget#130]
Hi! 
I tried to add my custom clips as described here:
https://imperavi.com/redactor/plugins/clips/
For this purposes i added next lines to config:
'plugins'     => [
                'clips'
 ],
 'clips' => [
     ['Test clip', '\<b class\=\"test-clip\"\>Test clip\<\/b\>']
 ]
But it doesn't work. Does this plugin support this functionality?

**Comment by vova07** [comment]
Hi @SlovyanskiyYehor ,
I've took a look at the plugin file that is used in my widget and so far it do not accept any external settings.
However if you need a fast solution you can go this way:

```php
# some-view.php

<?= \vova07\imperavi\Widget::widget([
        'name' => 'redactor',
        'settings' => [
            'plugins' => ['clips'],
            'clips' => [
                ['Test clip', '<span class="test-clip">Test clip</span>'],
            ],
        ],
    ]); ?>
```

And at the same time you need to adjust a bit the JS plugin: `src/assets/plugins/clips/clips.js`
Please replace this code:
```js
var items = [
    ['Lorem ipsum...', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'],
    ['Red label', '<span class="label-red">Label</span>']
];
```
with this one:
```js
if (this.opts.clips) {
    var items = this.opts.clips;
} else {
    var items = [
        ['Lorem ipsum...', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'],
        ['Red label', '<span class="label-red">Label</span>']
    ];
}
```

I'll prepare a new release but a bit later.

P.S For some reason the class insertion work only for `span` as templates. Not sure why.

**Comment by SlovyanskiyYehor** [comment]
Thanks for your response!
I did as you wrote and it works.
I hope in future you will add this fix to new release. I think that it's really important feature.

**Comment by vova07** [comment]
@SlovyanskiyYehor thanks for your feedback.
I'll try to adjust the widget asap.

**Comment by vova07** [comment]
Fixed by @bscheshirwork !
