### ISSUE TITLE
file.delete и file.deleted Callbaks не работают

### ISSUE THREAD

**Issue by sinergycode** [vova07/yii2-imperavi-widget#131]
@vova07 Добрый день.

Скажите пожалуйста что надо подправить в коде чтобы заработали Callbaks:
![image](https://user-images.githubusercontent.com/30791491/39507600-4dcbb0a8-4de7-11e8-81c1-1c308540959d.png)
```
<?= $form->field($model, 'text')->widget(Widget::className(), [
        'settings' => [
            'lang' => 'ro',
            'plugins' => [
                'filemanager',
              ],
            'fileDeleteCallback' => new \yii\web\JsExpression('function () { alert("File was deleted!"); }'),
            'fileDeletedCallback' => new \yii\web\JsExpression('function () { alert("File was deleted!"); }'),
         ],
]); ?>
```

**Comment by vova07** [comment]
Здравствуйте @sinergycode !
Извиняюсь за поздний ответ!

К сожалению вы используете несуществующие колбэки, по этому и ничего не происходит.
Рекомендую изучить документацию конкретной версии виджета чтобы понять набор доступных функций: https://imperavi.com/assets/pdf/redactor-documentation-10.pdf
В кратце, колбэки есть только для удаления изображений.

Желаю удачи!

**Comment by sinergycode** [comment]
Спасибо!
