### ISSUE TITLE
В html-теги добавляется конструкция "="",  что препятствует валидации AMP-страниц

### ISSUE THREAD

**Issue by enepochatova** [vova07/yii2-imperavi-widget#138]
Здравствуйте,

столкнулись с проблемой, что редактор добавляет в разметку символьную конструкцию такого плана:  <h3 "="">
После каких именно действиях это происходит - неизвестно. Т.к. выявили это уже постфактум, когда все тексты были уже давно заполнены. 
Такие теги являются невалидными для AMP страниц, это препятствует их индексации. 
Что это такое и можно ли это побороть? 

Спасибо.

**Comment by enepochatova** [comment]
@vova07 спасибо, по итогу добавили парсер, который исключает такие конструкции. 
При каких точно обстоятельствах такое возникает - не смогли быстро выяснить, поэтому отложили это исследование.

**Comment by vova07** [comment]
Спасибо что отписались.
Желаю удачи!

**Comment by solks** [comment]
Действительно, в моем случае "="" добавляется в теги <img >. Появляется после нажатия на картинке в редакторе.
Баг присутствует начиная с версии 1.2.7
