### ISSUE TITLE
Sticky блок 

### ISSUE THREAD

**Issue by dozer111** [vova07/yii2-imperavi-widget#141]
Здрастуйте vova07.
Пользуясь виджетом возникает необходимость, чтобы закрепить бар со всеми ресурсами вверху страницы при прокрутке. Отсюда вопрос: вы задумывали подобную функциональность, и если нет, то как лучше всего проредактировать ваш виджет, потому что я как jun часа 3 возился с js и полем, но облажался. 
Спасибо, надеюсь на ответ

**Comment by vova07** [comment]
Здравствйте @dozer111 ,
Извиняюсь за поздний ответ, но я не был в сети определенное время.

Для справки хочу сказать что я лишь автор обертки под `Yii2` и использую стороне расширение `JS` редактора, по этому все возможность ровно те что есть у редактора, не больше.

Касательно вашего вопроса я думаю что вам нужна опция: `toolbarFixed: true`. Более подробно можете прочитать про доступные опции в офф-документации расширения, вот тут: https://imperavi.com/assets/pdf/redactor-documentation-10.pdf поищите раздел `Toolbar`.

Надеюсь это информация будет для вас полезна.

Удачи!

**Comment by dozer111** [comment]
Доброй ночи Владимир, напоследок хочу оставить у вас эту ссылку, в которой содержится необходый пример, чтобы другие люди тоже могли быстро сориентироватся.
[https://imperavi.com/redactor/examples/toolbars/fixed-top-offset/](url)

**Comment by vova07** [comment]
Спасибо за ссылку!

Буду считать вопрос закрытым. Если что-то надо будет дополнить, вы в любой момент можете повторно открыть репорт.

С уважением, Василий! :)
