### ISSUE TITLE
Конструкция "="" в тегах <img>

### ISSUE THREAD

**Issue by solks** [vova07/yii2-imperavi-widget#142]
Видел, что подобная тема была, но закрыта из-за недостаточности информации об ошибке.
В моем случае "="" добавляется в теги &lt;img&gt;. Появляется после нажатия на картинке в редакторе, даже без открытия окна редактирования.
Баг присутствует начиная с версии 1.2.7

**Comment by solks** [comment]
Нашел ошибку в javascript коде, файл /src/assets/redactor.js 
строка 2111:
html = html.replace(/<(.*?)rel="\s*?"(.*?[^>]?)>/gi, '<$1$2">'); 
заменить на 
html = html.replace(/<(.*?)rel="\s*?"(.*?[^>]?)>/gi, '<$1$2>');

и строка 2112:
html = html.replace(/<(.*?)style="\s*?"(.*?[^>]?)>/gi, '<$1$2">');
заменить на 
html = html.replace(/<(.*?)style="\s*?"(.*?[^>]?)>/gi, '<$1$2>');

**Comment by vova07** [comment]
Спасибо @solks !
Фикс добавил в версии 2.0.6.
