### ISSUE TITLE
Как изменить список удаляемых тегов?

### ISSUE THREAD

**Issue by Dkalugin** [vova07/yii2-imperavi-widget#144]
Добрый день!
Подскажите, пожалуйста, как исключить из списка удаляемых тегов div?

**Comment by vova07** [comment]
Здравствуйте @Dkalugin ,
Можете чуть подробнее описать задачу?
Я не уверен что я понял вашего вопроса.
Иметься введу удаление в момент вставки текста в редактор?

**Comment by Dkalugin** [comment]
Переключаю редактор в режим HTML. Пишу <div><p>бла-бла-бла</p></div>. Переключаю обратно в визуальный режим. Снова переключаю в режим HTML. Вижу <p>бла-бла-бла</p>.
В документации (pdf) разработчика редактора нашел, что можно управлять списком удаляемых тегов. Но вот как его передать при использовании виджета - не соображу...

**Comment by Dkalugin** [comment]
Не работает... 
Вот код:
` 
<?
use vova07\imperavi\Widget;
?>

   <?= $form->field($model, 'about')->widget(Widget::className(), [
        'settings' => [
            'lang' => 'ru',
            'minHeight' => 200,
            'allowedTags' => ['p', 'h1', 'h2', 'div', 'b', 'i', 'u', 'strong', 'br', 'iframe', 'a'],
            'plugins' => [
                'clips',
                'fullscreen',
            ],
        ]
    ]); ?>`

Поведение не изменилось, снова все добавленные div удалились.

**Comment by vova07** [comment]
Мне кажется вам надо добавить еще `'replaceDivs' => false` опцию.
```php
field($model, 'about')->widget(Widget::className(), [ 'settings' => [ 'lang' => 'ru', 'minHeight' => 200, 'replaceDivs' => false, 'allowedTags' => ['p', 'h1', 'h2', 'div', 'b', 'i', 'u', 'strong', 'br', 'iframe', 'a'], 'plugins' => [ 'clips', 'fullscreen', ], ] ]);
```

**Comment by Dkalugin** [comment]
Да, так получилось. Большое спасибо!

**Comment by JamalAbsalimov** [comment]
Написал плагин свой который добавляет html код, в нем есть div span итд,  но при добавлений редактор удаляет div итд, а текст оборачивает в тэг p
Как сделать так что бы он не заменял на свои теги ?
