### ISSUE TITLE
Как разрешить отображение тега "script"

### ISSUE THREAD

**Issue by atomrus1993** [vova07/yii2-imperavi-widget#153]
Если в контенте содержится тег **script** он не отображается в редакторе, даже в режиме html, как можно это исправить?

**Comment by vova07** [comment]
Здравстуйте @atomrus1993 !

Вам надо добавить тэг в список доступных. 
Найдите по этой ссылке: https://imperavi.com/assets/pdf/redactor-documentation-10.pdf поиском параметр `allowedTags`.

В итоге будет что-то такое: 
```
echo \vova07\imperavi\Widget::widget([
    'name' => 'redactor',
    'settings' => [
        'lang' => 'ru',
        'allowedTags' => ['p', 'div', 'script', ...],
        ...
    ]
]);
```

**Comment by atomrus1993** [comment]
Здравствуйте @vova07 !

Пробовал делать так, и пробовал делать тег 
`removeScript => false`, 
не помогло, все равно не могу редактировать, не вижу скрипта...

**Comment by vova07** [comment]
@atomrus1993 вам надо удалить `script` из списка запрещенных тэгов.
Следующий код должен работать:
```php
echo \vova07\imperavi\Widget::widget([
    'name' => 'redactor',
    'settings' => [
        'lang' => 'ru',
        'deniedTags' => ['style'],
        ...
    ]
]);
```

Желаю удачи!

**Comment by atomrus1993** [comment]
@vova07  **Спасибо**! то что надо!)

**Comment by atomrus1993** [comment]
@vova07 Тикет можно закрыть! проблема полностью решена!)
Большая просьба к Вам @vova07 , добавить в readme такие моменты, для скрипта, для div'ов, чтобы при таких случаях не страдали люди))

Спасибо Вам!)

**Comment by mesrop0258** [comment]
Vova zdravstvuyte. ya ustanovil imperavi na yii2, xochu dobavit widget html code. nikak ne poluchaetsya, pojaluysta skajite kak eto sdelat

**Comment by atomrus1993** [comment]
Привет!) напишите мне в телеграмм @atomrus1993 я помогу) если vova не ответит
4 июня 2019 г., 13:00 +0300, mesrop0258 <notifications@github.com>, писал:
