### ISSUE TITLE
How to control buttons?

### ISSUE THREAD

**Issue by kwazaro** [vova07/yii2-imperavi-widget#157]
If I override "buttons" setting, the toolbar buttons has strange behavior. Some buttons doesn't show (even those, that appear by default). Is it a bug? How can I add or change default buttons?

**Comment by kwazaro** [comment]
The problem was with button names. On the Imperavi website there are different button names, like "undo", "redo", "ul", "ol"...
https://imperavi.com/redactor/docs/settings/button/#s-buttons
But it seems that doc is not for this version of redactor in this widget. So your button names like ['​html',​​'​formatting',​​'​bold',​​'​italic',​​'​deleted',​ 'unorderedlist',​​'​orderedlist',​​'​outdent',​​'​indent',​ 'image',​​'​file',​​'​link',​​'​alignment',​​'​horizontalrule']​ works well. Thanks!

**Comment by vova07** [comment]
Yes, the widget's redactor version is `10.x.x`, which is quite different from what is now on the website, as that one describe the new version instead.

**Comment by kwazaro** [comment]
Is it possible to upgrade widget's redactor version to latest one?

**Comment by vova07** [comment]
No, because of OEM.
The `Yii` community bought only OEM for `Redactor 10`.
