### ISSUE TITLE
Split options to own variables for usage with DI 

### ISSUE THREAD

**Issue by yujin1st** [vova07/yii2-imperavi-widget#19]
It convenient to use Dependency Injector to define default configuration for all project, but if you want to specify plugins or image\file options (imageUpload, fileUpload, imageGetJson) for particular view, all other settings become reseted. 
I suggest to define separate variables (buttons, plugins, imageUpload and etc) and implode them into settings while running the widget. Property "settings" will remain for backward compatibility... 
If you will agree, I can write a pull request.

**Comment by MadAnd** [comment]
Hi @vova07 and @yujin1st , 
I believe my PR #40 resolves this issue.

**Comment by vova07** [comment]
Fixed thanks!
