### ISSUE TITLE
Update to 10.0.8

### ISSUE THREAD

**Issue by a-komarev** [vova07/yii2-imperavi-widget#31]
Could you update your extension to newest version of script, please?
There is a fix in this build included from the [forum thread](http://www.yiiframework.com/forum/index.php/topic/62159-imperavi-redactor-widget-breaking/page__pid__275447#entry275447).

**Comment by vova07** [comment]
Well we'll need to wait for SamDark when he will update the redactor assets, because only he has the access to the redactor updates.
I'm just use the assets from this repo: https://github.com/yiiext/imperavi-redactor-widget because there no alternatives.

**Comment by a-komarev** [comment]
Ah... really, I forgot redactor is proprietary.

**Comment by a-komarev** [comment]
https://github.com/yiiext/imperavi-redactor-widget/releases/tag/v1.3.9

**Comment by a-komarev** [comment]
Thank you!

**Comment by vova07** [comment]
You're welcome!
