### ISSUE TITLE
Ability to define custom "clips"

### ISSUE THREAD

**Issue by mrbig00** [vova07/yii2-imperavi-widget#33]
I wanted to use custom defined "clips", but after configuring nothing happened. 

My code: 

    $form->field($model, 'attachment')->widget(Widget::className(), [
                        'settings' => [
                            'minHeight' => 200,
                            'imageManagerJson' => Url::to(['/site/images-get']),
                            'imageUpload' => Url::to(['/site/image-upload']),
                            'plugins' => [
                                'clips',
                                'imagemanager'
                            ],
                            'clipsJson' => '[{ "title": "TEST Button", "clip": "<a>This is a button</a>" }]'
                        ]

**Comment by vova07** [comment]
Hi @mrbig00 ,
I took a look to `clips.js` plugin, but if really I'm not sure how to configure this plugin. The [`items`](https://github.com/vova07/yii2-imperavi-widget/blob/480326bd5763799e61f6292ec9c924672a8ef152/src/assets/plugins/clips/clips.js#L8) variable is predefined, and there is no possibility to override it. I was searching for `clipsJson` but without success, can you provide a link to that documentation where you found that option?

**Comment by mrbig00** [comment]
I think I looked at the [wrong documentation] (https://www.modmore.com/extras/redactor/documentation/configuration/#clips+json), because it has the same name and look, never mind, my bad. 

Back to the issue: then I think the easiest way to include a customized copy of the plugin with the desired "clips".

**Comment by vova07** [comment]
Ok, I think you can try `'clipsJson' => [["button" ,"<button>This is a button</button>"]],` because in final this code will be encoded by the widget. Hope this will work for you.
