### ISSUE TITLE
No upload error message visible

### ISSUE THREAD

**Issue by marcovtwout** [vova07/yii2-imperavi-widget#35]
I added the widget and configured image uploads as described here: https://github.com/vova07/yii2-imperavi-widget#upload-image

I open the form page, click the add image button and pick a file. The modal closes, but the image is not visible, and no feedback message is visible. When I look in my network tab, I see the upload request returned a JSON response containing an error `{"error":"Het bestand \"IMG_9230.JPG\" is te groot. Het kan niet groter zijn dan 2.097.152 bytes."}`   (file too big)

![image](https://cloud.githubusercontent.com/assets/438046/6905768/9da499b4-d72a-11e4-9e40-6d960dfd1102.png)

**Comment by vova07** [comment]
It's an expected behavior.
You try to upload a file that is too big, so you get the error messages.
But if you wanna prompt this message or if you need something else, you may write your own callback. See this link: http://imperavi.com/redactor/docs/callbacks/image/ for more info.
So like an example you can write the follow code for simple `alert` error message:
```php
echo \vova07\imperavi\Widget::widget([
    'name' => 'redactor',
    'settings' => [
        'lang' => 'ru',
        'minHeight' => 200,
        'plugins' => [
            'clips',
            'fullscreen'
        ],
        'imageUploadErrorCallback' => new \yii\web\JsExpression('function(json){ alert(json.error); }')
    ]
]);
```

**Comment by marcovtwout** [comment]
I understand why the error is there, the problem is that the message is not displayed. Shouldn't there be a default error callback, for example the one that you posted?

**Comment by vova07** [comment]
I'll add this callback soon.

**Comment by Resmedia** [comment]
@vova07 Hello! And what about file error? I don't find file callback in code.
