### ISSUE TITLE
Ошибка в  FileHelper

### ISSUE THREAD

**Issue by aspire5738** [vova07/yii2-imperavi-widget#38]
При использовании плагина с изображениями не отображаються ищображения которые уже загружены на сервер.
![error](https://cloud.githubusercontent.com/assets/3993818/7215024/1f5f22e8-e5cd-11e4-8f49-9f524c37f1ea.png)
В дебагере браузера видно что в переменные thumb и image передаеться не url изображения, а путь к нему.
Настройки плагина:
```
'images-get' => [
    'class' => 'vova07\imperavi\actions\GetAction',
    'url' => 'http://my-site.dev/upload/images/', // Directory URL address, where files are stored.
    'path' => '@webroot/upload/images', // Or absolute path to directory where files are stored.
    'type' => GetAction::TYPE_IMAGES,                
],

'settings' => [
    'lang' => 'ru',
    'minHeight' => 200,
    'imageManagerJson' => Url::to(['/blog/post/images-get']),
    'imageUpload' => Url::to(['/blog/post/image-upload']),
    'plugins' => [
        'table',
        'imagemanager',
        'clips',
        'fullscreen',
    ]
]

```

**Comment by vova07** [comment]
Скрин дебагера можете тоже прикрепить пожалуйста?

**Comment by aspire5738** [comment]
![debug](https://cloud.githubusercontent.com/assets/3993818/7215214/79f4a5b8-e5d5-11e4-9780-8e90b0744955.png)

**Comment by vova07** [comment]
Не могу повторить ошибку. На `OS X` все работает как надо, на `Ubuntu` тоже, тесты в CI проходят, вероятнее всего дело в винде. Как я понимаю вы именно на `Windows` разрабатываете так?

**Comment by vova07** [comment]
Есть возможность проверить данный баг на Уникс системах?

**Comment by aspire5738** [comment]
Да вы правы работаю на Windows. Завтра будет возможность все это залить на сервак c Ubuntu. Отпишу о результате.

**Comment by aspire5738** [comment]
Ты оказался прав, на ubunte все прокатило. Придется копаться в настройках xampp. Спасибо за помощь.
