### ISSUE TITLE
Добавление своих плагинов

### ISSUE THREAD

**Issue by Insolita** [vova07/yii2-imperavi-widget#4]
'''
php

if (isset($this->settings['plugins'])) {
            $asset->plugins = $this->settings['plugins'];
        }
'''
Надо как-то отделить, или опцию отдельно для кастомных плагинов сделать,  которые своими ассетами вручную регистрироваться будут

**Comment by temirfe** [comment]
На офф сайте есть плагин Specialchars, которого нет в виджете по умолчанию. Пробовал добавить этот плагин по описанному выше методу:
1) скачал `specialchars.min.js` с офф сайта и залил в папку `frontend/web/js`
2) создал бандл `SpecialcharsAsset.php` в папке `frontend/assets` с таким контентом:
```
public $sourcePath = '@webroot';
    //public $basePath = '@webroot';
    //public $baseUrl = '@web';
    public $css = [];
    public $js = [
        'js/specialchars.min.js'
    ];
    public $depends = [
        'vova07\imperavi\Asset'
    ];
```
3) в форме где я использую виджет непосредственно:
```
<?php
    echo $form->field($model, 'text')->widget(ImperaviWidget::className(), [
        'settings' => [
            'lang' => 'ru',
            'minHeight' => 200,
            'maxHeight' => 400,
            'imageUpload' => Url::to(['/site/image-upload']),
            'imageManagerJson' => Url::to(['/site/images-get']),
            'plugins' => [
                'clips',
                'fullscreen',
                'imagemanager',
                'table',
                'specialchars'=> 'SpecialcharsAsset'
               // 'specialchars'=> 'frontend\assets\SpecialcharsAsset' //и так пробовал (метод 2)
            ],
        ],
    ]);
    ?>
```
и не работает. В консоле смотрю ошибка: `http://example.com/assets/6fbfea23/plugins/SpecialcharsAsset/SpecialcharsAsset.js 404 not found`
или `http://example.com/assets/6fbfea23/plugins/frontend/assets/SpecialcharsAsset/frontend/assets/SpecialcharsAsset.js 404 (Not Found)` в методе 2
что делать?

**Comment by vova07** [comment]
Здравствуйте @temirfe ,

У вас проблема в самом коде с настройками.
Перечитайте пожалуйста вот этот раздел документации: https://github.com/vova07/yii2-imperavi-widget/blob/master/README_RU.md#Регистрация-своих-плагинов

Вкратце вы должны использовать отдельный индекс `plugins` в массиве настроек который находиться на том-же уровне что и `settings`.

То есть у вас должен быть примерно такой код:
```php
[
    'settings' => [
        ...
        'plugins' => [...], // Тут подключаться дефолтные плагины.
        ...
    ],
    'plugins' => [
        'specialchars' => SpecialcharsAsset::class, // Тут вы добавляете свои кастомные плагины.
    ]
]
```

Желаю удачи!

**Comment by BeekeeperVS** [comment]
Подскажите. добавил плагин budfferbuttons. У мене несколько вкладок где используется редактор. в перевой вкладке погружаеться, в остальных просто отображается textarea. в чом может быть проблема?
