### ISSUE TITLE
Official version

### ISSUE THREAD

**Issue by freezy-sk** [vova07/yii2-imperavi-widget#41]
Hi
what about making this package official?
@samdark @cebe @qiangxue ?

**Comment by samdark** [comment]
There's no such plan.

**Comment by freezy-sk** [comment]
@samdark why? there is https://github.com/yiiext/imperavi-redactor-widget for v1

**Comment by cebe** [comment]
thats not official either...

**Comment by freezy-sk** [comment]
@cebe thanks. I saw @samdark on the list of contributors so I thought it's official when it's under yiiext.

**Comment by cebe** [comment]
yiiext is only a set of extensions that claim to follow certain standards and quality.
