### ISSUE TITLE
Uploading images to the same directory with the same name

### ISSUE THREAD

**Issue by arogachev** [vova07/yii2-imperavi-widget#43]
When `unique` is set to `false` and we upload image to the same directory with the same name, it simply overwrites previous one with the same name.

We can handle it like that:
- Throw exception (depending on option for example).
- Add confirmation window.

What do you think?

**Comment by vova07** [comment]
I think it can be a good idea.
Will add it in next releases. Or PR is welcome!

**Comment by vova07** [comment]
Added in https://github.com/vova07/yii2-imperavi-widget/pull/108
