### ISSUE TITLE
Video plugin not working

### ISSUE THREAD

**Issue by atmoz** [vova07/yii2-imperavi-widget#45]
Looks like it's working when editing, but after saving or toggling HTML mode, the youtube iframe is removed. Looks like iframes are not allowed. Tried tweaking deniedTags and allowedTags, but did not help.

Is the video plugin broken?

**Comment by vova07** [comment]
Does it works in `Imperavi` redactor without my wrapper? Probably it's the problem of redactor it self, not of my extension.

**Comment by atmoz** [comment]
Issue solved in version 10.2.1
