### ISSUE TITLE
update to 10.2.3

### ISSUE THREAD

**Issue by notgosu** [vova07/yii2-imperavi-widget#50]
Hi!

Please update redactor.js to latest version 10.2.3

**Comment by vova07** [comment]
We need to wait when "SamDark" will update his [repo](https://github.com/yiiext/imperavi-redactor-widget). I don't have access to redactor's updates.

**Comment by notgosu** [comment]
Sam updated his repo already.

**Comment by notgosu** [comment]
Thanks!
