### ISSUE TITLE
Setting not workin

### ISSUE THREAD

**Issue by balo85** [vova07/yii2-imperavi-widget#53]
Hello guys!
I have a problem with this widget. My code is
echo Form::widget([
    'model'       => $model,
    'form'        => $form,
    'columns'     => 1,
    'attributes'  => [
      'body'   => [
        'type'        => Form::INPUT_WIDGET,
        'widgetClass' => Redactor::className(),
        'settings'    => [
          'lang'        => 'it', 
          'minHeight'   => 200, 
          'plugins'     => [ 'text-direction' ]
        ]
      ],
    ]
  ]);
but hte minHeight is not working!
Even, how can i load the lang correctly?

Thanks!

**Comment by vova07** [comment]
I think you have some `css` problems. I check the `minHeight` param, and it work for me. 
Ensure that you don't have a `css` rule that override that height for textarea.
