### ISSUE TITLE
How to disable jquery?

### ISSUE THREAD

**Issue by zhukovsergey** [vova07/yii2-imperavi-widget#56]
Hi!
I'm did redefine **Asset**  comment _'yii\web\JqueryAsset'_ in **$depends**
And reload **registerClientScripts()** method in 

```
$asset = Yii::$container->get(\backend\assets\Imperavi::className());
```

But jquery whatever include ;[

**Comment by vova07** [comment]
[Here](https://github.com/vova07/yii2-imperavi-widget/blob/master/src/Asset.php#L49) is where the dependency is registered.
But I'm not sure that this editor is able to work without `jQuery`.
