### ISSUE TITLE
Проблема с двумя редакторами на странице

### ISSUE THREAD

**Issue by Sadykh** [vova07/yii2-imperavi-widget#57]
В общем, ситуация следующая.

Есть два вызова редактора на странице с доп. плагином.

``` php
<?= $form->field($model, 'first_content')->widget(\vova07\imperavi\Widget::className(), [
                'settings' => [
                    'lang' => 'ru',
                    'minHeight' => 200,
                    'plugins' => [
                        'clips',
                        'fullscreen',
                        'relink'
                    ],
                ],
                'plugins' => [
                    'relink' => 'app\assets\ServicePagesReLinks'
                ]

            ]); ?>


<?= $form->field($model, 'second_content')->widget(\vova07\imperavi\Widget::className(), [
                'settings' => [
                    'lang' => 'ru',
                    'minHeight' => 200,
                    'plugins' => [
                        'clips',
                        'fullscreen',
                        'relink'
                    ]
                ],
                'plugins' => [
                    'relink' => 'app\assets\ServicePagesReLinks'
                ]
            ]); ?>
```

Дело в том, что если я подключаю плагин relink один раз - проблем не возникает. Если же прописываю как в коде выше, второе текстовое поле вылетает с ошибкой и не может якобы найти файл (но в первом редакторе работает всё как надо:

> GET http://site.ru/zakaz/assets/71fb10c8/plugins/relink/relink.js 
> jquery.js:1458 Uncaught Error: Syntax error, unrecognized expression: a.re-[object Object]

Я косячу с выводом, или это баг?

**Comment by vova07** [comment]
Пока не могу сказать что это. Проверю по возможности и отпишусь.
Спасибо!

**Comment by vova07** [comment]
@Sadykh извиняюсь за столь поздний ответ.
Я понимаю что прошло много времени и мой ответ уже не актуален, но сегодня перед релизом новой версии проверил ваш случай.
К сожалению воспроизвести я не смог.
Два и более редактора с одинаковым набором кастомных плагинов работают корректно на одной странице.
Если проблема для вас еще актуально просьба повторно открыть эту тему.
Спасибо!
