### ISSUE TITLE
How to add source code plugin.

### ISSUE THREAD

**Issue by mohdbashir** [vova07/yii2-imperavi-widget#58]
i would like to add the html soucre code with "div , span " etc but default editor not supporting these html tags and replace with tag " p".

Please help to enable or support the Html tag in editor.

**Comment by vova07** [comment]
I'm not sure if I'am right because already a lot of time I didn't work with this editor, but maybe you can try to override the [`paste`](https://imperavi.com/redactor/docs/callbacks/paste/) callback.

**Comment by vova07** [comment]
Please reopen the issue if you think I can help you more.
