### ISSUE TITLE
Пора обновить список плагинов

### ISSUE THREAD

**Issue by voskobovich** [vova07/yii2-imperavi-widget#59]
Нужен плагин Source Code, которого нет.  
Планируется ли добавление новых плагинов?

**Comment by vova07** [comment]
Все доступные плагины я добавил!
Если что-то не хватает, то к сожалению я не могу с этим ничего поделать так как сам источник для меня служит репозиторий [плагина](https://github.com/yiiext/imperavi-redactor-widget) для первой версии.

**Comment by voskobovich** [comment]
А почему источник старый репо?
На офф сайте ведь новые плагины выставлены. Они бесплатны.

**Comment by vova07** [comment]
Источник старый так как это единственный источник откуда я могу брать новые версии.
Про плагины я не совсем в теме, по этому буду благодарен за ссылку.

**Comment by voskobovich** [comment]
Вот здесь можно найти все плагины, которые есть у тебя + новые
https://imperavi.com/redactor/plugins/

**Comment by voskobovich** [comment]
Так что с обновлением списка плагинов?
Вроде не сложно скачать на офф сайте и залить в репо. Или есть какие-то проблемы с лицензией и тд?

**Comment by vova07** [comment]
Извиняюсь за столь поздний ответ!
Сегодня перед релизом второй версии обертки, пробовал подключит плагины которые доступны на офф сайте, к сожалению они не совместимы с той версией редактора которая есть в данном репозитории.
Большинство ошибок из-за несуществующего метода `setIcon()`.
Если есть идеи как подружит их с версией из репозитория, или есть ссылки на совместимые версии пагинов буду признателен.
В случае необходимости откройте пожалуйста повторно эту тему!
Спасибо!
