### ISSUE TITLE
How to pass plugins settings without registering it as assets

### ISSUE THREAD

**Issue by djagya** [vova07/yii2-imperavi-widget#60]
I'm trying to pass my plugin to the editor:
```php
'settings' => [
    'plugins' => ['myplugin']
]
```

The problem is that the widget will register that plugin assuming we're using one of the basic plugins, as a result we get 404: `.../assets/8aa582f4/plugins/myplugin/myplugin.js `.

Should we maybe introduce an option to not to register plugin asset? Or add a const with all basic plugins available to check if needed plugin is your package and should be registered as asset or external.

**Comment by vova07** [comment]
Please check the documentation [here](https://github.com/vova07/yii2-imperavi-widget/blob/master/README.md#add-custom-plugins).
