### ISSUE TITLE
Delete table row

### ISSUE THREAD

**Issue by tolik505** [vova07/yii2-imperavi-widget#61]
Hi! Is it possible to delete table row in this redactor without using of source mode? I don't see item Delete row in the table dropdown list.

**Comment by vova07** [comment]
Hi,
I'm not sure I have a right answer for you, but it looks like a bug.
For more info I think you need to ask on developer's [website](https://imperavi.com).

**Comment by vova07** [comment]
I'll close this issue, if you think I could help, you are free to reopen it.
