### ISSUE TITLE
Пустая text-aria

### ISSUE THREAD

**Issue by wokster** [vova07/yii2-imperavi-widget#63]
Всегда все было норм, теперь делаю новый сайт, вставил редактор, в post запросе пусто, нет данных. Все облазил, в консоле ошибок нет, просто не отрпавляется, как будто нет поля в форме вовсе. В чем может быть проблема?

**Comment by wokster** [comment]
Сам нашел. Глючит в следующем случае
если форма началась в диве, который закрылся до редактора
<div><form></div>
<div>тут редвктор</div>
<div></form></div>

**Comment by vova07** [comment]
Не думаю что я смогу это как-то решить на стороне виджета.
Больше похоже на баг со стороны самого JS библиотеки.
