### ISSUE TITLE
Image rotation

### ISSUE THREAD

**Issue by jazzman** [vova07/yii2-imperavi-widget#65]
Sometimes redactor rotates vertical-oriented image 90 degree.

![update article 67](https://cloud.githubusercontent.com/assets/5958158/12443417/5acead2c-bf60-11e5-8fb5-6ad43f699bed.png)

**Comment by vova07** [comment]
Hi,
This is really late answer, sorry for that.
However I think it's not related with this specific implementation, and it's something with `Redactor` library.
In case you have a fix, please share your solution.
Thanks!
