### ISSUE TITLE
imageUpload 

### ISSUE THREAD

**Issue by AmadouD** [vova07/yii2-imperavi-widget#66]
what do you mean about default controller; i have to create a new controller under the extention 
or i have  to put this 
public function actions()
{
    return [
        'image-upload' => [
            'class' => 'vova07\imperavi\actions\UploadAction',
            'url' => 'http://my-site.com/images/', // Directory URL address, where files are stored.
            'path' => '@alias/to/my/path' // Or absolute path to directory where files are stored.
        ],
    ];
}
to my form controller .
i tried the second one but giving me      #   url   unknow
please give somme explanation about uploading file and image;
sorry for my bad english

**Comment by vova07** [comment]
Hi @AmadouD ,
You have put that code to your existing `controller` class.
The problem with `url` can have some relation with `routing` settings.  Maybe you forgot to add a `rule` to your `UrlManager configs` for that new `upload` action.

**Comment by AmadouD** [comment]
Hi @vova07 thank for your reponse its help me a lot !!
i have setup the configs in url manager but still didnt get the icon for image

he is my ofrresController
` public function actions()
     {

         
      return [
          'image-upload' => [
            'class' => 'vova07\imperavi\actions\UploadAction',
            'url' => Yii::$app->getUrlManager()->getBaseUrl().'/uploads/', // Directory URL address, where files are stored.
            'path' => Yii::$app->basePath.'/common/uploads/' // Or absolute path to directory where files are stored.

        ],
      ];

  }` 

and my _form
`<?= $form->field($model, 'description')->widget(Widget::className(), [
    'settings' => [
        'lang' => 'fr',
        'minHeight' => 200,
        'plugins' => [
            'fontfamily',
            'clips',
            'fullscreen',
            'imageUpload' => Url::to(['/offres/image-upload'])
        ]
        ]
       ]); ?>` 
note : i have already fix the problem with url.
any  idea what i am missing; i am new in advanced template

**Comment by vova07** [comment]
Not sure if that is a typo or not, but the problem I see is that 'imageUpload' option must be a key of 'settings' array not 'plugins'. Try to fix that to see the result. Sorry for missed exemple, writing from smartphone.

**Comment by AmadouD** [comment]
after putting      the    Url::to(['/offres/image-upload'])  outside the plugins
and put imagemanager, filemanager in plugings  it work fine 
thank you a lot;
great extensions i will put a star
