### ISSUE TITLE
Не создается события validateOnChange и validateOnBlur при использовании ajax в activeForm

### ISSUE THREAD

**Issue by wokster** [vova07/yii2-imperavi-widget#67]
Есть  ActiveForm c 
`'enableAjaxValidation' => true,
'enableClientValidation' => false,
`
validateOnChange и validateOnBlur включены по умолчанию. Но редактор не реагирует.
Как это пофиксить?

**Comment by vova07** [comment]
Ответ поздний но для истории оставлю коммент.
По мне это ожидаемое поведение, так как редактор заменяет само текстовое поле, таким образом события не срабатывают.
Вероятнее всего это можно решить через колбэки самого редактора.
Но конечно все это надо дописывать самостоятельно.
