### ISSUE TITLE
how can i add the undo redo buttons?

### ISSUE THREAD

**Issue by liyadongcn** [vova07/yii2-imperavi-widget#70]
<?php echo $form->field($model, 'content')->widget(Widget::className(), [
        'settings' => [
            'lang' => 'zh_cn',
            'minHeight' => 200,
            'imageUpload' => Url::to(['post/image-upload']),
            'buttons' => ['format' ,'bold', 'italic', 'deleted', 'lists', 
                            'image', 'file', 'link', 'horizontalrule','undo','redo'],
            'plugins' => [
                //'undoredo',
                //'redo',
                //'clips',
                //'fullscreen'
            ]
        ]
    ]);?>

format will be not availible and the undo redo do not work too.

Thanks.

**Comment by alex2549** [comment]
All what you need:
1) add bufferbuttons to plugins

'plugins' => [
                    'bufferbuttons',
 ]

2) Add js :
<script type="text/javascript">
(function($)
{
    $.Redactor.prototype.bufferbuttons = function()
    {
        return {
            init: function()
            {
                var undo = this.button.addFirst('undo', 'Undo');
                var redo = this.button.addAfter('undo', 'redo', 'Redo');
 
                this.button.addCallback(undo, this.buffer.undo);
                this.button.addCallback(redo, this.buffer.redo);

                this.button.setIcon(undo, '<i class="re-icon-undo"></i>');
                this.button.setIcon(redo, '<i class="re-icon-redo"></i>');
            }
        };
    };
})(jQuery);
</script>

useful link: https://imperavi.com/redactor/examples/buttons-undo-and-redo/

**Comment by vova07** [comment]
Thanks @alex2549 !
