### ISSUE TITLE
Redactor II?

### ISSUE THREAD

**Issue by marcovtwout** [vova07/yii2-imperavi-widget#73]
The included editor is outdated for more than 6 months, will it ever be updated? The website only shows documentation for the latest version, so it seems this plugin will be worthless.

**Comment by vova07** [comment]
The `Yii` community didn't bought license for `Redactor II` so it can't be updated.
With `Yii` you can use only `Redactor I` for free.
Sorry, but this is not my fault, it's the all right I have atm.
If someone will buy new license for second version, it will nice, and than, I'll update the extension.

**Comment by marcovtwout** [comment]
That's understandable, but could you mension this in the Readme maybe?
