### ISSUE TITLE
Imperavi Redactor Widget filemanager plugin localization

### ISSUE THREAD

**Issue by Belotur** [vova07/yii2-imperavi-widget#75]
Доброго дня. При подключении плагина загрузки изображений обнаружил проблему с локализацией кнопочек в диалоге выбора/загрузки изображения: они не локализуются (Upload и Choose).
Проблема решается заменой в файле /vendor/vova07/yii2-imperavi-widget/src/assets/plugins/filemanager/filemanager.js строчек 

`this.modal.addTab(1, 'Upload', 'active');`
`this.modal.addTab(2, 'Choose');`
на

`this.modal.addTab(1, this.lang.get('upload'), 'active');`
`this.modal.addTab(2, this.lang.get('choose'));`

Очень прошу модифицировать модуль. А то приходится после каждого апдейта вносить правку. Ну и с меня звёздочка :-).
Всего наилучшего.

**Comment by vova07** [comment]
Добавлено в https://github.com/vova07/yii2-imperavi-widget/pull/108
