### ISSUE TITLE
need update Imperavi Redactor to1.2.5 with jQuery 3 compatibility

### ISSUE THREAD

**Issue by almix** [vova07/yii2-imperavi-widget#77]
now problem with jQuery 3. Some menu buttons in Redactor don't work

**Comment by iovzt** [comment]
Просьба к автору обновить версию плагина до последней, желательно 1.3.0 или если нет времени - с удовольствием помогу, только дайте новую версию плагина)

**Comment by TrueXakeP** [comment]
As far as I know this is a limitation of all OEM licenses that they granted to a fixed software version without updates.

**Comment by TrueXakeP** [comment]
Look at #59.

**Comment by asmythe** [comment]
hear! hear!

**Comment by EkaterinaBuyakova** [comment]
what's here? we have uncorrect work with jquery 3.

**Comment by vova07** [comment]
https://github.com/vova07/yii2-imperavi-widget/issues/104
