### ISSUE TITLE
Вставка скриншота

### ISSUE THREAD

**Issue by GT-Volk** [vova07/yii2-imperavi-widget#78]
Доброго времени суток.
К сожаление не могу заставить работать вставку скриншотов.
Консоль ругается:
`VM102:1 The given range isn't in document. 
addRange @ VM102:1 
set @ VM102:1 
setEnd @ VM102:1 
setAfter @ VM102:1 
execHtml @ VM102:1 
html @ VM102:1 
insert @ VM102:1 
(anonymous function) @ VM102:1 
proxy @ jquery.js:497` 
Попытка нагуглить проблему не увенчалась успехом. 
Возможно кто то уже сталкивался с данной проблемой и нашел ее решение.

**Comment by mat-test** [comment]
А чем отличается от загрузки изображений? Или я что-то не понимаю...

**Comment by GT-Volk** [comment]
Я имел в виду вставку изображения из буфера обмена в редактор. Как выяснилось  на платной версии редактора такой проблемы нет.

**Comment by vova07** [comment]
Очень поздний ответ, извиняюсь!
Протестил  сегодня эту ситуацию.
Баг присутствует, подтверждаю, но к сожалению исправить это я не могу. Тут проблема не в обертке, а в самом JS плагине.
Если есть знающие люди которые могут с этим помочь пожалуйста откройте заново эту тему и обсудим.
Спасибо!
