### ISSUE TITLE
Codemirror Plugin

### ISSUE THREAD

**Issue by mat-test** [vova07/yii2-imperavi-widget#82]
Василий, день добрый! Добавь, пожалуйста, плагин Codemirror, если не сложно...

https://imperavi.com/redactor/plugins/codemirror/

**Comment by vova07** [comment]
Приветную!
Очень поздний ответ, за что я дико извиняюсь.
Перед сегодняшним релизом новой версии я пробовал добавить этот плагин. К сожалению на текущей версии редактора он не завелся. Проблема в несуществующем методе `setIcon()`.
Если есть идеи как это можно решить, буду признателен.

**Comment by vova07** [comment]
Я закрываю этот репорт.
Если вы думаете что он еще актуален и у вас есть ответ на мой вопрос, то смело открывайте его заново.
Спасибо!
