### ISSUE TITLE
Транслит имени файлов при загрузке

### ISSUE THREAD

**Issue by celsoft** [vova07/yii2-imperavi-widget#83]
Хотелось бы видеть из коробки такую функцию. С возможностью выбора. Делать транслит или нет. Я сделал себе так:
```
if ($this->translit === true && $model->file->extension) {
     $model->file->name = Inflector::slug($model->file->baseName) . '.' . $model->file->extension;
 }
```

**Comment by vova07** [comment]
Добавлено в https://github.com/vova07/yii2-imperavi-widget/pull/108
