### ISSUE TITLE
Update Plugin

### ISSUE THREAD

**Issue by edsonrb2008** [vova07/yii2-imperavi-widget#88]
Does not work the plugin https://imperavi.com/redactor/plugins/properties/ please could update the plugin.

**Comment by vova07** [comment]
I would like to note that this wrapper is top on old version of `Imperavi Redactor` so I'm not bale to update the plugin.
Also I depend from official yii extension repo which host all originals redactor source file.
I can update only to that version.
So I'm not sure if that is possible.

**Comment by vova07** [comment]
This is issue is not related with this widget implementation.
Current extension is a yii2 wrapper only for `Redactor 10` which is different from new version.
