### ISSUE TITLE
Chrome 58 not able to format bold, italic, underline, sup, sub etc. for selected text

### ISSUE THREAD

**Issue by Mi7teR** [vova07/yii2-imperavi-widget#89]
http://stackoverflow.com/questions/43674400/redactor-editor-text-format-issues-with-chrome-version-58
solution there

**Comment by the0rist** [comment]
The same shit... :-(

**Comment by dmitry-grasevich** [comment]
+1 have the same issue ((

**Comment by webadequate** [comment]
Overall you can do like that:
rewrite **setMarker** function:
```
 setMarker: function (range, node, type) {
          var nclone = window.getSelection().getRangeAt(0).cloneRange();
          range = range.cloneRange();
          try {
            var selection = window.getSelection();
            range.collapse(type);
            range.insertNode(node);

            selection.removeAllRanges();
            selection.addRange(nclone);
          }
          catch (e)
          {
            this.focus.setStart();
          }
        },
```
or add fix in createMarkers function:
```
// Provided solution is tested for Redactor version 10.1.1
createMarkers: function()
    {
      this.selection.get();

      var node1 = this.selection.getMarker(1);

      this.selection.setMarker(this.range, node1, true);

      if (this.range.collapsed === false)
      {
        var node2 = this.selection.getMarker(2);
        this.selection.setMarker(this.range, node2, false);

        // Fix for Chrome58 Issues
        if (this.utils.browser('chrome')) {
              this.caret.set(node1, 0, node2, 0);
         }
         // End Chrome58 Issues
      }

      this.savedSel = this.$editor.html();
    },
```

**Comment by suneelkorada** [comment]
I tried to apply above resolution to fix the issue in Redactor 10.2.3. But I am getting an error in runtime where multiple redactor editor are there on the page. It is working fine for single instance of redactor.
Error: `Uncaught TypeError: Cannot read property 'setStart' of undefined
    at init.<anonymous> (redactor.js:1431)
    at HTMLDivElement.i (jquery.min.js:2)`

Could you please check this scenario and help me in fixing it ?

**Comment by suneelkorada** [comment]
Hi @webadequate , I am also having same issue and i want to apply above fix for my redactor externally. I mean writing an override for redactor. I stuck with overriding `createMarkers` method, could you please suggest me the way i can override it. I am using redactor 10.2.3.

**Comment by onmotion** [comment]
#97 should fix it, but minified js must be regenerated

**Comment by Cytosan** [comment]
I've created a PR with the regenerated minified js https://github.com/vova07/yii2-imperavi-widget/pull/98

**Comment by vova07** [comment]
Thank you all!
Especially @onmotion and @Cytosan .
The issue was fixed in this PR: https://github.com/vova07/yii2-imperavi-widget/pull/101
