### ISSUE TITLE
Ошибка на модалке "Изображение - Choose "

### ISSUE THREAD

**Issue by PROloggg** [vova07/yii2-imperavi-widget#93]
В инспекторе светится ошибка:
"Access level to vova07\imperavi\helpers\FileHelper::normalizeOptions() must be protected (as in class yii\helpers\BaseFileHelper) or weaker" и не отображаются загруженные ранее изображения.
Если, как сказано в ошибке, изменить метод vova07\imperavi\helpers\FileHelper::normalizeOptions() c private на protected, то работает и загруженные фото отображаются.

**Comment by vova07** [comment]
Fixed in https://github.com/vova07/yii2-imperavi-widget/pull/108
