### ISSUE TITLE
Incorrect thumbnail generation if path is symlink (on Windows)

### ISSUE THREAD

**Issue by zakdma** [vova07/yii2-imperavi-widget#94]
If I use symlinked folder (on Windows) for images it create incorrect URLs of thumbnails.
Example
I have real folder e:\Content\images
And I have symlinked folder d:\Content => e:\Content
So dir = d:\Content\images
There is code that convert dir to real path. It is also convert symlinks to real path (side effect).
https://github.com/vova07/yii2-imperavi-widget/blob/master/src/helpers/FileHelper.php#L38
But below you use old dir path not converted one.
https://github.com/vova07/yii2-imperavi-widget/blob/master/src/helpers/FileHelper.php#L53
It is strange.

**Comment by vova07** [comment]
Fixed in https://github.com/vova07/yii2-imperavi-widget/pull/108
