### ISSUE TITLE
Problems when page is not found

### ISSUE THREAD

**Issue by prsolucoes** [vova07/yii2-imperavi-widget#99]
https://github.com/vova07/yii2-imperavi-widget/blob/0e719a3f1d4fadfe8f6de2ed506a15dd8b16535d/src/Widget.php#L202

Problems when page is not found

When i try upload to invalid url or error 500 url, it shows a alert with message "true". Can you validate for erros 404/500 and show another message?

Thanks.

**Comment by vova07** [comment]
Fixed in https://github.com/vova07/yii2-imperavi-widget/pull/108
